### ISSUE TITLE
Get an enum value by String

### ISSUE THREAD

**Issue by komape** [leisim/dartx#104]
# Get an enum value by String

Would be nice, if the an enum would have by default a method like `getValue(String key)` that returns the corresponding enum value to that `key`. 

## Current situation

Currently it's necessary to iterate through the `values` and match them manually.

```dart
enum MyEnum {
  a, b, c, d
}
```

```dart
String key = 'c';
for(final MyEnum myEnum in MyEnum.values) {
  if(myEnum.toString() == key) return myEnum);
}
// optional fallback value
return MyEnum.a;
```

## Better solution

```dart
enum MyEnum {
  a, b, c, d
}
```

```dart
String key = 'c';
MyEnum myEnum = MyEnum.getValue(key, fallback: MyEnum.a);
```

**Comment by passsy** [comment]
Currently not possible. Dart doesn't allow to define static extensions or factory constructors as extensions https://github.com/dart-lang/language/issues/723
