### ISSUE TITLE
List.map() with access to the current index

### ISSUE THREAD

**Issue by komape** [leisim/dartx#105]
# List.map() with access to the current index

The `List.map()` function should have access to the index such as in JavaScript.

```javascript
List myList = ['a', 'b', 'c'];

myList.map((val, index) {
  // so something
});
```

# Current Situation

The `List.map()` has only access to the value.

```dart
List myList = ['a', 'b', 'c'];

myList.map((val) {
  // do something
});
```

The working but ugly alternative is to use `asMap()` and iterate through its entries.

```dart
myList.asMap().entries.map((val) {
  final int index = val.key;
  // do something
}
```

# Better Solution

Give access to the index.

```dart
List myList = ['a', 'b', 'c'];

myList.map((val, index) {
  // so something
});
```

**Comment by komape** [comment]
Just found out, that the current alternative can be done this way

```dart
myList.asMap().map((index, val) {
  // do something
}
```

Still not perfect but little bit better.

**Comment by passsy** [comment]
We already support it. The method is called [`mapIndexed`](https://github.com/leisim/dartx/blob/master/lib/src/iterable.dart#L628)
