### ISSUE TITLE
[Feature request] Unique for list

### ISSUE THREAD

**Issue by shinriyo** [leisim/dartx#108]
I want to like this.
```
var ids = [1, 4, 4, 4, 5, 6, 6];
 var distinctIds = ids.toSet().toList();
// => [1, 4, 5, 6]
```

in dartx.
```
ids.unique();
```

**Comment by passsy** [comment]
We already have `distinct()` and `distinctBy()` https://github.com/leisim/dartx/blob/b488b172f336b67de20ea7183f717389a9287c39/lib/src/iterable.dart#L657-L683

**Comment by shinriyo** [comment]
ah, okey.
like SQL's name.
I just research by "unique" word
so I couldn't find.
