### ISSUE TITLE
Breaks json_serializable

### ISSUE THREAD

**Issue by muhleder** [leisim/dartx#15]
This currently breaks any models using json_serializable if imported into the model file.

https://pub.dev/packages/json_serializable

E.g. if dartx is imported into the example.dart in the above link,

then the example fromJson generated code goes from 

```
Person _$PersonFromJson(Map<String, dynamic> json) {
  return Person(
    firstName: json['firstName'] as String,
    lastName: json['lastName'] as String,
    dateOfBirth: DateTime.parse(json['dateOfBirth'] as String),
  );
}
```

to 

```
Person _$PersonFromJson(Map<String, dynamic> json) {
  return Person(
    firstName: json['firstName'],
    lastName: json['lastName'],
    dateOfBirth: json['dateOfBirth'],
  );
}
```

I believe the extensions here applied directly to the types are breaking the type checking in the json_serializable helper functions.

https://github.com/dart-lang/json_serializable/tree/master/json_serializable/lib/src/type_helpers

It seems that using generic extensions would stop this breaking.

i.e. in https://github.com/leisim/dartx/blob/master/lib/src/string.dart instead of 

`extension StringX on String {`

use

`extension StringX<T extends String> on T {`

**Comment by leisim** [comment]
This seems to be a bug in `json_serializable` or in the `analyzer`. I don't think we should make all extensions generic...
