### ISSUE TITLE
`takeFirst` and `takeLast` are not index safe

### ISSUE THREAD

**Issue by philippschweig** [leisim/dartx#155]
[`takeFirst`](https://github.com/leisim/dartx/blob/master/lib/src/iterable.dart#L523) and [`takeLast`](https://github.com/leisim/dartx/blob/master/lib/src/iterable.dart#L539) are not index safe.

Excerpt of `takeFirst`: sublist is not index safe
```
extension IterableTakeFirst<E> on Iterable<E> {
  List<E> takeFirst(int n) {
    final list = this is List<E> ? this as List<E> : toList();
    return list.sublist(0, n);
  }
}
```

**Comment by passsy** [comment]
Already fixed #156
