### ISSUE TITLE
Do we need `invoke` method?

### ISSUE THREAD

**Issue by wurikiji** [leisim/dartx#16]
Dart, basically, supports the`call()` method for all `Function`s. So we can already use `myFunction?.call()`.  In addition, `call()` method can take any number of arguments.

**Comment by wurikiji** [comment]
This is implicitly documented on [Callable Classes](https://dart.dev/guides/language/language-tour#callable-classes).

**Comment by leisim** [comment]
Oh I didn't know that ^^
I'll deprecate and remove the `invoke()` method.

**Comment by wurikiji** [comment]
:) Because this package is getting popular if you write what I said to your README, it will be really helpful for others who also don't know about this. Thanks for your works on this package 😍

**Comment by shinayser** [comment]
This package will be getting very popular now that 2.7 as hit stable for Flutter 😆

**Comment by leisim** [comment]
Do you get code completion for the `.call()` method because I don't. Maybe that would be an argument against removing `.invoke()`.

**Comment by shinayser** [comment]
> Do you get code completion for the `.call()` method because I don't. Maybe that would be an argument against removing `.invoke()`.

None completion. But the completion on dart is really weird. I will post this issue on the language repo.

**Comment by shinayser** [comment]
Done. Give it a thumbs up to help it enter on developers radar :)

https://github.com/dart-lang/sdk/issues/39761

**Comment by passsy** [comment]
The deprecation is a good solution!
