### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [leisim/dartx#173]
Kindly consider adding a privacy manifest to your library following the new apple policy by adding PrivacyInfo.xcprivacy file to your project.

For more information check [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

**Comment by passsy** [comment]
dartx has no native ios code. A privacy manifest is not required by apple.

dartx is also not listed as SDK that requires a manifest https://developer.apple.com/support/third-party-SDK-requirements/
