### ISSUE TITLE
coerceIn is unnecessary

### ISSUE THREAD

**Issue by wkornewald** [leisim/dartx#18]
If I understand coerceIn correctly it does the same thing as num.clamp:
https://api.dartlang.org/stable/2.7.0/dart-core/num/clamp.html

The other two coerce methods do the same thing as min() and max(). Maybe your methods are slightly easier to understand, but min and max are so common in other programming languages that keeping the convention might be more important than introducing a second way to do the same thing. If you still want to keep the methods maybe you could at least change the implementation to use min / max instead of the more verbose comparison.

**Comment by leisim** [comment]
I did not even know `clamp()` existed. I'm not sure about how to move forward. Many users come from Kotlin and maybe we should keep some duplicates for them.

This is also related to #10 and #16

**Comment by leisim** [comment]
We decided to keep some duplicate methods to make finding them easier for new users (for example Kotlin users)
