### ISSUE TITLE
Move `sum` operations to another extension on `Iterable<num>`.

### ISSUE THREAD

**Issue by lrhn** [leisim/dartx#2]
The `sum` operations in `IterableX` cast their elements to `num`.
Consider instead having an 
```dart
extension IterableNumX<T extends num> on Iterable<T> { 
  T sum() {  ... }
  ...
}
```
Then you don't need to cast each element (but you will have to be a little clever about finding the correct `0` for the iteration, perhaps:
```dart
T sum() {
  T result = 0 is T ? 0 as T : 0.0 as T;
  for (var value in this) result += value;
  return result;
}
```

**Comment by leisim** [comment]
I'll do that, thanks...
