### ISSUE TITLE
Add '.count' method to Lists and maps

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [leisim/dartx#22]
I'd like to submit a PR for this when I get time unless someone adds it before me. Basically it would take the same parameters as a where function and will return the number of elements in the list or map that satisfy the condition

**Comment by leisim** [comment]
This method [already exists](https://github.com/leisim/dartx/blob/825040aeba9f2fd88a716c90294fd65b06144ee5/lib/src/iterable.dart#L402) on `Iterables`. How would you implement it on maps?

**Comment by ThinkDigitalSoftware** [comment]
I can't find an existing count method. Do you have a link to the docs?
For map you'd find all map entries that satisfy a condition and return the
count of them

**Comment by leisim** [comment]
https://pub.dev/documentation/dartx/latest/dartx/IterableX/count.html

**Comment by ThinkDigitalSoftware** [comment]
Oh, I thought you meant natively. Ok. I missed it. It's cause I incorrectly
assumed that what was in the Readme was all that was there

**Comment by leisim** [comment]
I think this issue is resolved. Please reopen if you still have a problem.
