### ISSUE TITLE
MD5 getter doesn't work on windows

### ISSUE THREAD

**Issue by jinyus** [leisim/dartx#26]
`print('abc'.md5);`
the code above outputs "O°Ö?}(ár"

This is what I got when I ran the test:

00:01 +18 -1: StringX .md5) [E]
  Expected: 'd41d8cd98f00b204e9800998ecf8427e'
    Actual: 'Ô\x1DÙ\x00²\x04é\tøB~'
     Which: is different.
            Expected: d41d8cd98f ...
              Actual: Ô\x1DÙ\x ...
                      ^
             Differ at offset 0

  package:test_api                      expect
  ..\dartx\test\string_test.dart 126:7  main.<fn>.<fn>

**Comment by leisim** [comment]
Thanks for opening this issue. This has already been solved with #21 and will be part of the next release.

**Comment by leisim** [comment]
This has been fixed with the latest version.
