### ISSUE TITLE
Add Iterable.groupBy

### ISSUE THREAD

**Issue by deadsoul44** [leisim/dartx#50]
It is available as a function:
https://api.flutter.dev/flutter/package-collection_collection/groupBy.html

But, it can be more useful as an extension. 

There is a discussion on dart-lang repo but the issue is closed:
https://github.com/dart-lang/sdk/issues/30376

**Comment by passsy** [comment]
It's already available
-> [`Iterable<T>.groupBy`](https://github.com/leisim/dartx/blob/da180dd4033c6460294e29a810c0a7ef3a18cc0e/lib/src/iterable.dart#L983)
