### ISSUE TITLE
coerceIn is already a feature of num

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [leisim/dartx#60]
Using `num.clamp(lower,upper)`, it returns the same thing.

**Comment by leisim** [comment]
There are multiple discussions around duplicate names (#49) and we decided to keep the duplicate versions and rely on tree shaking to get rid of the unused ones...

**Comment by ThinkDigitalSoftware** [comment]
> There are multiple discussions around duplicate names (#49) and we decided to keep the duplicate versions and rely on tree shaking to get rid of the unused ones...

Understood. I followed the links and came to the same conclusion. Your reasoning makes sense to me. I think then in these cases, it can simply be a wrapper that calls the other function rather than reimplementing it, as `coerceIn` currently does. A second option can be to mark the alias function, in this case, `coerceIn` as deprecated to facilitate teaching new ones the Dart way of doing things.
