### ISSUE TITLE
Can I add ELEMENT between LIST of ELEMENTS?

### ISSUE THREAD

**Issue by ianjaspersantos** [leisim/dartx#64]
````dart
// List of Texts
final texts = <Widget>[
    Text('text1'),
    Text('text2'),
    Text('text3'),
];

// Extension Functionality
texts.insertDivider(Divider());

// Output
<Widget>[
    Text('text1'),
    Divider()
    Text('text2'),
    Divider()
    Text('text3'),
];
````

Is there any way I can achieve this using this packages easily? Thanks

**Comment by xsahil03x** [comment]
This package is specific to Dart extensions, flutter extensions should be added to "[FlutterX](https://pub.dev/packages/flutterx)".

The repository link is currently broken, @leisim will be able to guide you more on this.

**Comment by passsy** [comment]
I'm using this extension in my projects

```dart
import 'package:flutter/widgets.dart';
import 'package:dartx/dartx.dart';

extension WidgetListExt on Iterable<Widget> {
  /// adds widgets between the elements
  List<Widget> dividedWith(Widget divider) {
    final elements = flatMap((it) => [it, divider]).toList();
    // remove last divider
    return elements.dropLast(1);
  }
}
```

**Comment by ianjaspersantos** [comment]
Thanks for the answer. :)
But somewhat somehow I think its relevant to dartx as it should be flexible as possible like the use case below:

````dart
final words = <String>[
    'Hello',
    'Flutter',
    'Community',
];

//Accepted value should be based on the generic class type passed
final newWords = words.dividedWith(' '); 
````

But ill the extension you provided. Thank you!

**Comment by passsy** [comment]
@ianjaspersantos You can use [Iterable<T>.joinToString()](https://github.com/leisim/dartx/blob/8b2617855f444a9058074b4a90cbd7ea1926fa7e/lib/src/iterable.dart#L269)
