### ISSUE TITLE
Add whereNotNull method to Iterable

### ISSUE THREAD

**Issue by marcelgarus** [leisim/dartx#66]
Great to filter Iterables.
Will be even more helpful when NNBD lands.

**Comment by rrousselGit** [comment]
Maybe:

```dart
List<int> list = <int?>[].where.isNotNull;
```

**Comment by passsy** [comment]
[`whereNotNull`](https://pub.dev/documentation/dartx/latest/dartx/IterableX/whereNotNull.html) already exists.

We have to see how it will work with NNBD. Right now it returns `Iterable<E>` where `E` can be nullable. Not sure if the type system allows to return a generic non-null type.

**Comment by rrousselGit** [comment]
> [`whereNotNull`](https://pub.dev/documentation/dartx/latest/dartx/IterableX/whereNotNull.html) already exists.
> 
> We have to see how it will work with NNBD. Right now it returns `Iterable<E>` where `E` can be nullable. Not sure if the type system allows to return a generic non-null type.

It should be feasible to write:

```dart
extension <T> on Iterable<T?> {
  Iterable<T> get whereNotNull =>... 
}
