### ISSUE TITLE
path version conflict

### ISSUE THREAD

**Issue by passsy** [leisim/dartx#77]
`dartx: 0.4.0` is incompatible with Flutter `1.17` because of `path`.

```yaml
dependencies:
  flutter:
    sdk: flutter
  dartx: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

```bash
$ flutter packages get
Because every version of flutter_test from sdk depends on path 1.6.4 and dartx 0.4.0 depends on path ^1.7.0, flutter_test from sdk is incompatible with dartx 0.4.0.
And because no versions of dartx match >0.4.0 <0.5.0, flutter_test from sdk is incompatible with dartx ^0.4.0.
So, because spitch depends on both dartx ^0.4.0 and flutter_test any from sdk, version solving failed.
```

**Comment by passsy** [comment]
The version range can't be expanded to include earlier versions of `path` because dartx depends on the new [`extension(String path, [int level])`](https://pub.dev/documentation/path/latest/path/Context/extension.html) method added to `path: 1.7.0`.

For most users it should be fine to override the path dependency:

```yaml
dependency_overrides:
  path: ^1.7.0
```

**Comment by mreichelt** [comment]
Yep, I'm affected by this. Wouldn't it make more sense to create regular versions for stable, and `-dev` or `-beta` versions for those who use Flutter Dev or Beta? It's kind of weird to force users into using builds not marked as stable.

**Comment by shinayser** [comment]
Flutter 1.18 is the one that is being promoted to stable soon? I think it's the 1.17 right?

If it's the 1.17 the workaround 2 will not be possible for quite some time (until the next release I believe).

**Comment by passsy** [comment]
Flutter 1.17 is the next stable version

**Comment by passsy** [comment]
`dartx: ^0.4.1` is now compatible with Flutter 1.17 (stable)
