### ISSUE TITLE
Add String.removePrefix, removeSuffix, and removeSurrounding

### ISSUE THREAD

**Issue by mreichelt** [leisim/dartx#79]
I know these methods from Kotlin: they make development so much easier when you need those.

- `removePrefix`: removes a prefix from a string and returns that as a copy, otherwise returns a copy of the original string
- `removeSuffix`: same, but for suffix.
- `removeSurrounding`: removes a prefix and a suffix if and only if both exist - otherwise keeps that unchanged. Run [this Kotlin example](https://pl.kotl.in/gHyZlMRy_).

Would love to implement those as well!

**Comment by passsy** [comment]
Absolutely go for it! We're missing tons of useful String manipulation extensions.

I've seen similar methods in other extension packages. Have a look there for some inspiration
- Googles `dart_basic` offers [`withoutPrefix`](https://github.com/google/dart-basics/blob/390c4649c63373f7144b453aeb9824d2c9599746/lib/string_basics.dart#L42) and [`withoutSuffix`](https://github.com/google/dart-basics/blob/390c4649c63373f7144b453aeb9824d2c9599746/lib/string_basics.dart#L56).
- `dart_extensions_methods` offers [`replaceBefore`](https://github.com/mishatron/dart_extensions/blob/75a4aebc4057b78e2dc42f931afe6ec35f1f35a0/lib/dart_extensions_methods.dart#L95) and [`replaceAfter`](https://github.com/mishatron/dart_extensions/blob/75a4aebc4057b78e2dc42f931afe6ec35f1f35a0/lib/dart_extensions_methods.dart#L85)
