### ISSUE TITLE
flutterx should become a separate repository

### ISSUE THREAD

**Issue by passsy** [leisim/dartx#8]
I don't see value in having `dartx` and `flutterx` in the same repository. I'd prefer moving `flutterx` to `leisim/flutterx` and keep both separate.

**Comment by leisim** [comment]
Yes you are probably right. Especially since I also plan to create `testx`.

**Comment by leisim** [comment]
I thought it would be nice to have everything in one place but I think I'll split them...

**Comment by mnordine** [comment]
@leisim Same for `time.dart`

**Comment by leisim** [comment]
@mnordine time.dart is already a [seperate repository](https://github.com/jogboms/time.dart)...

**Comment by mnordine** [comment]
Ah, I misunderstood. I thought the issue was for simply re-exporting other libraries, as you're doing with `time.dart`. I don't see why you should do that?

**Comment by leisim** [comment]
> I don't see why you should do that?

#11
