### ISSUE TITLE
Correct file to add this extension.

### ISSUE THREAD

**Issue by xsahil03x** [leisim/dartx#89]
@passsy can you suggest the correct file to add this particular [extension function](https://gist.github.com/xsahil03x/be1c66d521f7e1f1195a6149c33ba538). I don't really think this should be part of String extension.

```dart
extension StringX on String {
  /// Creates a `Duration` object from an ISO8601 formatted string.
  ///
  /// This method parses out a subset of the ISO8601 duration format. As years
  /// and months are not of a set length this method does not support that. We
  /// are then left with support for weeks, days, hours, minutes and seconds.
  Duration get toDuration {
    if (!RegExp(
            r"^(-|\+)?P(?:([-+]?[0-9,.]*)Y)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)W)?(?:([-+]?[0-9,.]*)D)?(?:T(?:([-+]?[0-9,.]*)H)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)S)?)?$")
        .hasMatch(this)) {
      throw ArgumentError("String does not follow correct format");
    }

    final weeks = _parseTime(this, "W");
    final days = _parseTime(this, "D");
    final hours = _parseTime(this, "H");
    final minutes = _parseTime(this, "M");
    final seconds = _parseTime(this, "S");

    return Duration(
      days: days + (weeks * 7),
      hours: hours,
      minutes: minutes,
      seconds: seconds,
    );
  }

  /// Private helper method for extracting a time value from the ISO8601 string.
  int _parseTime(String duration, String timeUnit) {
    final timeMatch = RegExp(r"\d+" + timeUnit).firstMatch(duration);

    if (timeMatch == null) {
      return 0;
    }
    final timeString = timeMatch.group(0);
    return int.parse(timeString.substring(0, timeString.length - 1));
  }
}
```

**Comment by leisim** [comment]
There are countless time formats. Not sure if it is a good idea to add parsing for one specific format (even if it is a common one)...

**Comment by xsahil03x** [comment]
@leisim makes sense, Closing.

**Comment by passsy** [comment]
isn't this a duplicate of [DateTime.parse](https://api.dart.dev/stable/1.24.3/dart-core/DateTime/parse.html) anyways?

**Comment by passsy** [comment]
[DateTime](https://api.dart.dev/stable/1.24.3/dart-core/DateTime/parse.html) supports parsing of ISO8601 timestamps. I think it would be a good idea to offer the same for `Duration`. 

I personally would prefer an official `Duration.parse()` constructor in the dart sdk, which probably takes years to land.

I don't like offering an extension for `String` for such a rarely used method. Therefore `dartx` might not be the perfect place for this method.
I could see it as a top-level method in [`time`](https://pub.dev/packages/time), or in parsing libraries like [`deep_pick`](https://pub.dev/packages/deep_pick) as a `.asDateTime()` extension.
