### ISSUE TITLE
add forEachIndexed for list

### ISSUE THREAD

**Issue by nateshmbhat** [leisim/dartx#97]
Many times we would need index along with value. This extension could help a lot when added to a list.

**Comment by passsy** [comment]
It's already implemented for `Iterable`, therefore also for `List`
https://github.com/leisim/dartx/blob/bbfb05da04d2b596eaa097ddc98f302e8f09bb92/lib/src/iterable.dart#L159-L164

**Comment by nateshmbhat** [comment]
i guess its not documented in the readme 🤔

**Comment by passsy** [comment]
Thanks for bringing it up. Wanna open a PR to fix it?

**Comment by nateshmbhat** [comment]
Sure :) would love to ✌️
